### ISSUE TITLE
Mail sent without attached QR image

### ISSUE THREAD

**Issue by Nauttor** [sciguy14/LibeTech-QR-WebSystem#1]
Dear Jeremy, 

I try your code and it fail to send the attached QR code on my system. The mail leef my sendmail and it arrive at my mail server, but on the code of the mail the attach is reffer as: `<img src="cid:attach">` without any qr image. I check if the hash is correctly created and it´s ok on the valid.txt. 

Maybe it´s a problem with the googleapi url, it appears they deprecate the old api, however the url still works and generate QR via web. 

Any help would be appreciate. 

Regards

**Comment by Nauttor** [comment]
The problem was that the /code directory was not created. Now it works. Just in case someone have the same error.

**Comment by greedfall** [comment]
hello, can you teach me step by step how to setup this program? please

**Comment by sciguy14** [comment]
Please do not ressurect closed issues. The instructions are in the readme and the files - I'm not actively supporting this project anymore. If you have a specific issue that you find, you can open a new issue instead of commenting on an existing one. Thanks for understanding.
